services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: todo-server
    image: hossam7amdy/todo-server
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://root:pass@mongo:27017/
    env_file:
      - .env
    depends_on:
      - mongo
