services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadminsusr
      MONGO_INITDB_ROOT_PASSWORD: mongoadminpassword
      MONGO_INITDB_DATABASE: todo
    ports:
      - '27017:27017'
    networks:
      - todo-network

  mongodb_admin:
    image: mongo-express:latest
    container_name: mongo-admin
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadminsusr
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongoadminpassword
      - ME_CONFIG_MONGODB_URL=mongodb://mongoadminsusr:mongoadminpassword@mongodb:27017/mydb?ssl=false&authSource=admin&directConnection=true
    networks:
      - todo-network
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: server
    image: todo-server
    ports:
      - 3000:3000
    networks:
      - todo-network
    environment:
      DATABASE_URL: mongodb://mongoadminsusr:mongoadminpassword@mongodb:27017/todo?authSource=admin
    env_file:
      - .env
    depends_on:
      - mongodb

networks:
  todo-network:
    driver: bridge
