services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    networks:
      - todo-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - todo-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: todo-server
    image: todo-server
    ports:
      - 3000:3000
    networks:
      - todo-network
    environment:
      MONGO_URI: mongodb://root:pass@mongo:27017/todo
    env_file:
      - .env
    depends_on:
      - mongo

networks:
  todo-network:
    driver: bridge
