name: Deploy to AWS EC2

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: hossam7amdy/todo-server
  CONTAINER_NAME: todo-server

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: docker-build
    runs-on: self-hosted
    steps:
      - name: Delete old images
        run: |
          docker image prune -f --filter "until=24h" || true

      - name: Stop and delete old container
        run: |
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

      - name: Pull image from docker hub
        run: |
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run new container
        run: |
          docker run --env-file /home/ec2-user/.env --name ${{ env.CONTAINER_NAME }} -dp 80:80 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
